server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: craftsman
  thymeleaf:
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.1.20:8096/jmzx_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: jmzx_dev
    username: jmzx_dev
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5

security:
  browser:
    loginPage: /login
    defaultFailureUrl: /login?error
logging:
  level:
    org:
      springframework:
        web: debug
        jdbc:
          datasource: debug
    java:
      sql: debug
    com:
      springboot:
        craftsman:
          dao:
            mapper: TRACE

  pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql